/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_JNI_Canlib */

#ifndef _Included_com_example_JNI_Canlib
#define _Included_com_example_JNI_Canlib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_JNI_Canlib
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_JNI_Canlib_initialize
  (JNIEnv *, jobject);

/*
 * Class:     com_example_JNI_Canlib
 * Method:    openChannel
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_JNI_Canlib_openChannel
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_JNI_Canlib
 * Method:    setBusParams
 * Signature: (IJIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_example_JNI_Canlib_setBusParams
  (JNIEnv *, jobject, jint, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     com_example_JNI_Canlib
 * Method:    busOn
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_JNI_Canlib_busOn
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_JNI_Canlib
 * Method:    readWait
 * Signature: (II)Lcom/example/JNI/CanMessage;
 */
JNIEXPORT jobject JNICALL Java_com_example_JNI_Canlib_readWait
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_JNI_Canlib
 * Method:    bussOff
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_JNI_Canlib_bussOff
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_JNI_Canlib
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_JNI_Canlib_close
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
